### ISSUE TITLE
Obtaining `client_secret.json` from Google Drive

### ISSUE THREAD

**Issue by petecooper** [sebastianfeldmann/phpbu-google-drive#3]
This issue is likely to be out of scope for the repository, but I wanted to check. I know this is not a support form as such, but someone might know…

Does anyone know how to get the relevant Google Drive JSON for the 2021 era admin interface? I have been pulling my hair out trying to get the credentials out of Google Drive (via a pay-for Google Workspace account) and I am getting nowhere fast _at all_.

I will continue investigating at this side, and I may turn this into a blog post if I eventually figure it out!

Thank you, and best wishes.

**Comment by sebastianfeldmann** [comment]
Sorry couldn't find it either :(

**Comment by petecooper** [comment]
Thanks @sebastianfeldmann - I'll close this now and contact you when I have a solution, I will offer a written guide or manual update if it's useful to you.

**Comment by hectorh30** [comment]
Sorry for posting on a closed issue, but did you find anything? I'm at the same point here

**Comment by petecooper** [comment]
Sadly no progress, @hectorh30.

**Comment by alivsaffari** [comment]
I'm using this file: [Google Developer Documents](https://developers.google.com/workspace/guides/create-credentials#create_credentials_for_a_service_account)
But still get an error: `missing the required redirect URI`
I don't know if I'm doing the right way or not!
